### PR TITLE
Sort properties before adding them to the schema.

### PR DESCRIPTION
**Pull request by tkvw**
Very small feature request, makes looking at the schema more friendly.

### CODE REVIEW

**Comment by jameskleeh** [comment]
To do this properly would require respecting https://github.com/grails/grails-data-mapping/blob/master/grails-datastore-gorm-validation/src/main/groovy/grails/gorm/validation/Constrained.groovy#L82

**Comment by jameskleeh** [comment]
You would also have to add an `order` property to custom properties as well so they could participate in the ordering

**Comment by jameskleeh** [comment]
See https://github.com/grails/scaffolding/blob/master/core/src/main/groovy/org/grails/scaffolding/model/property/DomainPropertyImpl.groovy#L110 for an example

**Comment by tkvw** [comment]
changing

**Comment by tkvw** [comment]
Retry

**Pull request merged**
